// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mprktoulahqmbclnviqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wcmt0b3VsYWhxbWJjbG52aXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNDA5NzUsImV4cCI6MjA2MTgxNjk3NX0.KxNRPyGt4WAIlUUC28w-k7HlNoG6KZjzoCNw7EE2-BI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);